name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: "Build & Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install Node.js dependencies
        run: npm install
      - name: Hexo Generate
        run: npm run build && rm public/robots.txt
      - name: Hexo Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_DEPLOY_KEY }}
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "$PRIVATE_KEY")
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          npm run deploy
